# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: archivo.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'archivo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rarchivo.proto\x12\x13\x61nalitica_seguridad\"4\n\x0b\x46iltroAnios\x12\x13\n\x0b\x61nio_inicio\x18\x01 \x01(\x05\x12\x10\n\x08\x61nio_fin\x18\x02 \x01(\x05\"5\n\x0eItemFrecuencia\x12\x11\n\tcategoria\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61ntidad\x18\x02 \x01(\x05\"J\n\x14RespuestaFrecuencias\x12\x32\n\x05\x64\x61tos\x18\x01 \x03(\x0b\x32#.analitica_seguridad.ItemFrecuencia\"A\n\x0eRespuestaTabla\x12\x16\n\x0ejson_dataframe\x18\x01 \x01(\t\x12\x17\n\x0ftotal_registros\x18\x02 \x01(\x05\x32\xb0\x03\n\x0eMotorAnalitica\x12k\n\x1aObtenerFrecuenciaProvincia\x12 .analitica_seguridad.FiltroAnios\x1a).analitica_seguridad.RespuestaFrecuencias\"\x00\x12\x66\n\x15ObtenerFrecuenciaArma\x12 .analitica_seguridad.FiltroAnios\x1a).analitica_seguridad.RespuestaFrecuencias\"\x00\x12i\n\x18ObtenerAgregacionInicial\x12 .analitica_seguridad.FiltroAnios\x1a).analitica_seguridad.RespuestaFrecuencias\"\x00\x12^\n\x13ObtenerResumenTabla\x12 .analitica_seguridad.FiltroAnios\x1a#.analitica_seguridad.RespuestaTabla\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'archivo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILTROANIOS']._serialized_start=38
  _globals['_FILTROANIOS']._serialized_end=90
  _globals['_ITEMFRECUENCIA']._serialized_start=92
  _globals['_ITEMFRECUENCIA']._serialized_end=145
  _globals['_RESPUESTAFRECUENCIAS']._serialized_start=147
  _globals['_RESPUESTAFRECUENCIAS']._serialized_end=221
  _globals['_RESPUESTATABLA']._serialized_start=223
  _globals['_RESPUESTATABLA']._serialized_end=288
  _globals['_MOTORANALITICA']._serialized_start=291
  _globals['_MOTORANALITICA']._serialized_end=723
# @@protoc_insertion_point(module_scope)
