# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import archivo_pb2 as archivo__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in archivo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MotorAnaliticaStub:
    """Interfaz eficiente y bien tipificada para el motor de cálculo
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObtenerFrecuenciaProvincia = channel.unary_unary(
                '/analitica_seguridad.MotorAnalitica/ObtenerFrecuenciaProvincia',
                request_serializer=archivo__pb2.FiltroAnios.SerializeToString,
                response_deserializer=archivo__pb2.RespuestaFrecuencias.FromString,
                _registered_method=True)
        self.ObtenerFrecuenciaArma = channel.unary_unary(
                '/analitica_seguridad.MotorAnalitica/ObtenerFrecuenciaArma',
                request_serializer=archivo__pb2.FiltroAnios.SerializeToString,
                response_deserializer=archivo__pb2.RespuestaFrecuencias.FromString,
                _registered_method=True)
        self.ObtenerAgregacionInicial = channel.unary_unary(
                '/analitica_seguridad.MotorAnalitica/ObtenerAgregacionInicial',
                request_serializer=archivo__pb2.FiltroAnios.SerializeToString,
                response_deserializer=archivo__pb2.RespuestaFrecuencias.FromString,
                _registered_method=True)
        self.ObtenerResumenTabla = channel.unary_unary(
                '/analitica_seguridad.MotorAnalitica/ObtenerResumenTabla',
                request_serializer=archivo__pb2.FiltroAnios.SerializeToString,
                response_deserializer=archivo__pb2.RespuestaTabla.FromString,
                _registered_method=True)


class MotorAnaliticaServicer:
    """Interfaz eficiente y bien tipificada para el motor de cálculo
    """

    def ObtenerFrecuenciaProvincia(self, request, context):
        """1. Solicita la distribución de frecuencias por Provincia
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerFrecuenciaArma(self, request, context):
        """2. Solicita la frecuencia de incidentes según el Tipo de Arma
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerAgregacionInicial(self, request, context):
        """3. Solicita el conteo total de casos por categoría (Homicidio, Asesinato, Sicariato y Femicidio)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerResumenTabla(self, request, context):
        """4. Solicita el resumen inicial de la tabla cargada para el Dashboard
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MotorAnaliticaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObtenerFrecuenciaProvincia': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerFrecuenciaProvincia,
                    request_deserializer=archivo__pb2.FiltroAnios.FromString,
                    response_serializer=archivo__pb2.RespuestaFrecuencias.SerializeToString,
            ),
            'ObtenerFrecuenciaArma': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerFrecuenciaArma,
                    request_deserializer=archivo__pb2.FiltroAnios.FromString,
                    response_serializer=archivo__pb2.RespuestaFrecuencias.SerializeToString,
            ),
            'ObtenerAgregacionInicial': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerAgregacionInicial,
                    request_deserializer=archivo__pb2.FiltroAnios.FromString,
                    response_serializer=archivo__pb2.RespuestaFrecuencias.SerializeToString,
            ),
            'ObtenerResumenTabla': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerResumenTabla,
                    request_deserializer=archivo__pb2.FiltroAnios.FromString,
                    response_serializer=archivo__pb2.RespuestaTabla.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analitica_seguridad.MotorAnalitica', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analitica_seguridad.MotorAnalitica', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MotorAnalitica:
    """Interfaz eficiente y bien tipificada para el motor de cálculo
    """

    @staticmethod
    def ObtenerFrecuenciaProvincia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analitica_seguridad.MotorAnalitica/ObtenerFrecuenciaProvincia',
            archivo__pb2.FiltroAnios.SerializeToString,
            archivo__pb2.RespuestaFrecuencias.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerFrecuenciaArma(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analitica_seguridad.MotorAnalitica/ObtenerFrecuenciaArma',
            archivo__pb2.FiltroAnios.SerializeToString,
            archivo__pb2.RespuestaFrecuencias.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerAgregacionInicial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analitica_seguridad.MotorAnalitica/ObtenerAgregacionInicial',
            archivo__pb2.FiltroAnios.SerializeToString,
            archivo__pb2.RespuestaFrecuencias.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerResumenTabla(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analitica_seguridad.MotorAnalitica/ObtenerResumenTabla',
            archivo__pb2.FiltroAnios.SerializeToString,
            archivo__pb2.RespuestaTabla.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
